// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Signix.IAM.Context;

namespace Signix.IAM.Context
{
    public partial class IAMDbContext
    {

        [DbFunction("fn_GetHexUniqueId", "dbo")]
        public static string fn_GetHexUniqueId(long? seqNumber)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
