// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Signix.IAM.Context;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Signix.IAM.Context
{
    public partial class IAMDbContext
    {
        private IIAMDbContextProcedures _procedures;

        public virtual IIAMDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new IAMDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IIAMDbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class IAMDbContextProcedures : IIAMDbContextProcedures
    {
        private readonly IAMDbContext _context;

        public IAMDbContextProcedures(IAMDbContext context)
        {
            _context = context;
        }
    }
}
