// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Signix.Entities.Entities;

[PrimaryKey("PermissionId", "RoleId")]
[Index("ModifiedById", Name = "IDX_RolePermissions_ModifiedById")]
[Index("RoleId", Name = "IDX_RolePermissions_RoleId")]
[Index("PermissionId", Name = "IX_RolePermissions_PermissionId")]
public partial class RolePermission
{
    [Key]
    public int RoleId { get; set; }

    [Key]
    public int PermissionId { get; set; }

    public bool IsActive { get; set; }

    public int? ModifiedById { get; set; }

    [ForeignKey("PermissionId")]
    [InverseProperty("RolePermissions")]
    public virtual Permission Permission { get; set; } = null!;

    [ForeignKey("RoleId")]
    [InverseProperty("RolePermissions")]
    public virtual Role Role { get; set; } = null!;
}