// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Signix.Entities.Entities;

namespace VIA.IAM.Entities;

[Index("UniqueId", Name = "IDX_UserRoles_UniqueId")]
[Index("UserId", Name = "IDX_UserRoles_UserId")]
[Index("UserId", "RoleId", Name = "UQ_UserRoles_UserId_RoleId", IsUnique = true)]
public partial class UserRole
{
    [Key]
    public int Id { get; set; }

    public int UserId { get; set; }

    public int RoleId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? UniqueId { get; set; }
   
    public DateTimeOffset CreatedDateTime { get; set; }

    public int? CreatedById { get; set; }

    public int? ModifiedById { get; set; }

    [ForeignKey("CreatedById")]
    [InverseProperty("UserRoleCreatedBies")]
    public virtual User? CreatedBy { get; set; }

    [ForeignKey("ModifiedById")]
    [InverseProperty("UserRoleModifiedBies")]
    public virtual User? ModifiedBy { get; set; }
    
    [ForeignKey("UserId")]
    [InverseProperty("UserRoleUsers")]
    public virtual User User { get; set; } = null!;
   
}